# Generated by Django 2.0.2 on 2018-03-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='votes',
            name='runoff',
            field=models.BooleanField(default=False),
        ),
    ]
